<?php

namespace DDVue\AdminPanel\app\Http\Controllers;

use App\Http\Controllers\Controller;
use DDVue\AdminPanel\app\Models\DdvueMenu;
use DDVue\Crud\Controllers\CrudController;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;


class AdminMenuController extends CrudController
{
    /**
     * @var DdvueMenu
     */
    private $ddvueMenu;

    /**
     * AdminMenuController constructor.
     *
     * @param DdvueMenu $ddvueMenu
     */
    public function __construct(DdvueMenu $ddvueMenu)
    {
        parent::__construct();
        $this->ddvueMenu = $ddvueMenu;
    }

    public function setup()
    {
        $this->crud->route = 'Ddvue.AdminPanel.menu';
//        $this->crud->permissionName = 'department';
        $this->crud->indexRecursive = true;
        $this->crud->title          = '后台菜单';
        $this->crud->viewName       = 'ddvue.adminpanel::pages.menu';
        $this->crud->setModel(DdvueMenu::class);

//        $this->crud->setPermissionName('list.department');

        parent::setup();

    }

    public function getIndex()
    {
        return parent::getIndex(); // TODO: Change the autogenerated stub
    }


    public function indexJson()
    {
        $r = $this->ddvueMenu->getAllByParentId();

        return json_encode($r);
    }

    public function getAdd()
    {
        $this->data['menus'] = $this->ddvueMenu->getSelectArrayByParentId(0,true);

        return parent::getAdd(); // TODO: Change the autogenerated stub
    }

    public function postAdd(Request $request = null)
    {
        return parent::storeCrud($request); // TODO: Change the autogenerated stub
    }

    public function getEdit($id)
    {
        return parent::getEdit($id); // TODO: Change the autogenerated stub
    }

    public function postEdit(Request $request = null)
    {
        return parent::updateCrud($request); // TODO: Change the autogenerated stub
    }


    public function del($selectionJson)
    {
        return parent::del($selectionJson); // TODO: Change the autogenerated stub
    }


}